#spring.application.name=accounts
spring:
  application:
    name: "accounts"
#  profiles:
#    active: "prod"

build:
  version: 3.0

accounts:
  message: "Welcome to EazyBank accounts related local APIs222222"
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345




